services:
  controller-app:
      build: ./controller_app
      networks:
        - project-network
      ports:
        - "3000:5000"
      restart: always
      environment:
        AWS_ACCESS_KEY_ID:
        AWS_SECRET_ACCESS_KEY:
        AWS_DEFAULT_REGION:
        EKS_CLUSTER_NAME: web-scrapping-demo
        ECS_CLUSTER_NAME: web-scrapping-demo-ecs
        SCRAPE_IMAGE_URI:
        BUCKET_NAME:
        DYNAMO_DB_TABLE_NAME: web-scrapping
        PUBLIC_SUBNETS:
        SECURITY_GROUPS:
        TASK_DEFINITION: web-scrapping-app:1
  dashboard-app:
      depends_on:
        - controller-app
      build: ./dashboard
      networks:
        - project-network
      ports:
        - "5000:5000"
      restart: always
      environment:
        AWS_ACCESS_KEY_ID:
        AWS_SECRET_ACCESS_KEY:
        AWS_DEFAULT_REGION:
        DYNAMO_DB_TABLE: web-scrapping
networks:
  project-network:
    driver: bridge
  